name: megalovania
description: Forget me not

publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_local_notifications: ^2.0.2
  path: ^1.7.0
  sqflite: ^1.3.1+2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
